### ISSUE TITLE
IE11 input focus issue

### ISSUE THREAD

**Issue by claudiuciumedean** [DanmarksAdresser/dawa-autocomplete2#8]
In IE11, if the container of the address suggestions has a maximum-height, making the container to have an overflow which can be visible by dragging the scroll bar,  it is not possible to use the arrows on the scroll bar or drag the scroll bar.

I have investigated this problem and it is an IE11 related issue as the input is losing focus when trying to scroll in the container, thus the blur event is triggered and the suggestions are removed.

![bug](https://user-images.githubusercontent.com/17252102/55145014-3e836280-5142-11e9-9706-f4471a24b1af.png)

**Comment by andershessellund** [comment]
Thanks for your bug report.

We never really intended for the autocomplete suggestions to support a scroll bar. I think would be a better solution to just display fewer suggestions, requiring the user to enter some more text instead.

If you have any suggestions for how the problem could be fixed, I will take a look at it. Otherwise, we will probably not prioritise the issue, as there is a workaround (not using the scroll bar) and it only affects a small and dwindling percentage of users, as the bug only affects IE11.

**Comment by claudiuciumedean** [comment]
I am working on fixing the bug right now, as soon as I am done with it, I will create a pull request and then you can investigate it.

**Comment by claudiuciumedean** [comment]
if(document.activeElement === inputElm.parentNode) {
      return;
 }

This if statement added in the blurHandler function actually solves the issue.

**Comment by andershessellund** [comment]
Thanks. I will take a look at it when we release the next version of the autocomplete component. This will probably be mid april.

**Comment by claudiuciumedean** [comment]
actually I have found a better fix for this issue, apparently the attribute: unselectable="on", placed on the suggestions container solves it.

**Comment by andershessellund** [comment]
Thanks for the fix. I have applied the unselectable="on" fix to master.
